; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24215.1 

; Generated by VC++ for Common Language Runtime
.file "D:\Murder\TMP\.NETFramework,Version=v4.0.AssemblyAttributes.cpp"
